title: Joey Marianer
email: me@joeym.org
description: "Joey Marianer: Software developer, UI enthusiast, tinkerer, homeowner, pedant."
url: "http://joeym.org"
markdown: kramdown
gems:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:title"
